
 <link rel="stylesheet" type="text/css" href="/client/cache/css/common/jquery-easyui-1.3.4/themes/default/easyui.css"
 id="swicth-style">
 <link rel="stylesheet" type="text/css" href="/client/cache/css/common/jquery-easyui-1.3.4/themes/icon.css"
 id="swicth-style">
 <!--  <link rel="stylesheet" type="text/css" href="/client/cache/css/admin/admin.css"
 id="swicth-style"> -->
 <script type="text/javascript" src="/client/cache/js/common/jquery-1.9.1.min.js"></script>
 <script type="text/javascript" src="/client/cache/js/common/jquery-easyui-1.3.4/jquery.easyui.min.js">
 </script>
  <script type="text/javascript" src="/client/cache/js/common/jquery-easyui-1.3.4/locale/easyui-lang-zh_CN.js">
 </script>
 <script type="text/javascript" src="/client/cache/js/common/jquery.form.js"></script>
 <script type="text/javascript" src="/client/cache/js/common/jquery.nano.js"></script>           
 <script type="text/javascript" src="/client/cache/js/common/json.js"></script>
 <script type="text/javascript" src="/client/cache/js/common/jquery.radio.js"></script>
        
